name: "BGG Portfolio Generator"
description: "GitHub Action to generate a static portfolio website from a BoardGameGeek account"
branding:
  icon: image
  color: orange
inputs:
  bgg_username:
    description: "The BoardGameGeek account to generate the portfolio for"
    required: true
  bgg_password:
    description: "The password of the BoardGameGeek account to authenticate with (either 'bgg_password' or 'bgg_token' is required)."
    required: false
  bgg_token:
    description: "A BoardGameGeek API access token to authenticate with (either 'bgg_token' or 'bgg_password' is required)."
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install jan-wennrich/bgg-portfolio-generator
      run: composer create-project jan-wennrich/bgg-portfolio-generator . --no-dev --no-progress
      shell: bash

    - name: Run generator
      run: php bin/bgg-portfolio-generator.php generate "${{ inputs.bgg_username }}" --bgg-token="${{ inputs.bgg_token }}" --bgg-password="${{ inputs.bgg_password }}"
      shell: bash
